function [models, vars] = ens_model_update(models, data, vars, params)
% [models, vars] = ens_model_update(models, data, vars, params)
% Fits an ensemble of models to the data.
%

    for model_name = string(fieldnames(models))'

        % Fit each sub-model
        [models.(model_name), vars.(model_name)] = feval( ...
                params.models.(model_name).update_script, ...
                models.(model_name), ...
                data, ...
                vars.(model_name), ...
                params.models.(model_name).params ...
            );

    end

end