function model = gpr_model_setup(config, data)
% model = gpr_model_setup(config, data)
% Fits new Gaussian process model to data
%

    model = fitrgp( ...
        data.Load', data.Power', ...
        'KernelFunction', config.params.KernelFunction, ...
        'KernelParameters', config.params.KernelParameters' ...
    );

end