block:
    NumContStates: 0
    NumDiscStates: 0
    NumOutputs: 5
    NumInputs: 11
    DirFeedthrough: 1
    NumSampleTimes: 1
    x0: []
    tss: [250, 0]
simulation:
    name: "test"
    params:
        t_stop: 4000
        PMax: 1580
machines:
    machine_1:
        name: "Machine 1"
        model: "model_1"
        trainingData: "machine_1_data.csv"
        params:
            op_limits: [56, 220]
            n_ss: 2
            x_tol: 2
            y_tol: 5
    machine_2:
        name: "Machine 2"
        model: "model_2"
        trainingData: "machine_2_data.csv"
        params:
            op_limits: [237, 537]
            n_ss: 2
            x_tol: 2
            y_tol: 5
    machine_3:
        name: "Machine 3"
        model: "model_3"
        trainingData: "machine_3_data.csv"
        params:
            op_limits: [194, 795]
            n_ss: 2
            x_tol: 2
            y_tol: 5
    machine_4:
        name: "Machine 4"
        model: "model_3"
        trainingData: "machine_4_data.csv"
        params:
            op_limits: [194, 795]
            n_ss: 2
            x_tol: 2
            y_tol: 5
    machine_5:
        name: "Machine 5"
        model: "model_3"
        trainingData: "machine_5_data.csv"
        params:
            op_limits: [194, 795]
            n_ss: 2
            x_tol: 2
            y_tol: 5
models:
    model_1:
        setupFcn: "ens_model_setup"
        predictFcn: "ens_model_predict"
        updateFcn: "ens_model_update"
        params:
            predictorNames: "Load"
            responseNames: "Power"
            models:
                model_11:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly1'
                model_12:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly2'
                model_13:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly3'
    model_2:
        setupFcn: "ens_model_setup"
        predictFcn: "ens_model_predict"
        updateFcn: "ens_model_update"
        params:
            predictorNames: "Load"
            responseNames: "Power"
            models:
                model_21:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly1'
                model_22:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly2'
                model_23:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly3'
    model_3:
        setupFcn: "ens_model_setup"
        predictFcn: "ens_model_predict"
        updateFcn: "ens_model_update"
        params:
            predictorNames: "Load"
            responseNames: "Power"
            models:
                model_31:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly1'
                model_32:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly2'
                model_33:
                    setupFcn: "fit_model_setup"
                    predictFcn: "fit_model_predict"
                    updateFcn: "fit_model_update"
                    params:
                        predictorNames: "Load"
                        responseNames: "Power"
                        significance: 0.1
                        fit:
                            fitType: 'poly3'
optimizer:
    obj_func: "LoadObjFun"
    X0: [56.1, 237.1, 194.1, 194.1, 194.1]
    A: []
    B: []
    Aeq: []
    Beq: []
    LB: [56, 237, 194, 194, 194]
    UB: [220, 537, 795, 795, 795]
    const_func: "MaxPowerConstraint"
    optimoptions:
        MaxIterations: 2000
        Display: "final-detailed"
    params:
        n_searches: 10
        z: 1000
        PMax: 1580