simulation:
    model:
        filename: "multiple_generators_els_2021b.mdl"
    inputs:
        filename: "load_sequence_11.mat"
    params:
        t_stop: 4000
        PMax: 1580
system:
    config_filename: "sys_config.yaml"
optimizer:
    config_filename: "opt_config.yaml"